In [6]:
import numpy as np
import opengm

gm=opengm.gm([2,2,2,2], operator='multiplier')

fA = np.array([0.3, 0.7])
fAB = np.array([[0.2, 0.8],
               [0.7, 0.3]])
fAC = np.array([[0.4, 0.6],
               [0.3, 0.7]])
fBCD = np.array([
        [
        [2, 8],
        [0.3, 0.7]
    ],
        [
        [0.6, 0.4],
        [0.7, 0.3]
    ]
])

gm.addFactor(gm.addFunction(fA),[0])
gm.addFactor(gm.addFunction(fAB),[0, 1])
gm.addFactor(gm.addFunction(fAC),[0, 2])
gm.addFactor(gm.addFunction(fBCD), [1, 2, 3])

3

In [11]:
import numpy

from time import time

gm, vs = gm.fixVariables([3], [1])

class PyCallback(object):
    def __init__(self):
        pass
    def begin(self,inference):
        print "begin"
    def end(self,inference):
        print "end"
    def visit(self,inference):
        print "visit"
        arg=inference.arg()
        gm=inference.gm()
        print "energy ",gm.evaluate(arg)
        print "marginals", inf.marginals(0)


callback=PyCallback()
visitor=inf.pythonVisitor(callback,visitNth=1)

inf=opengm.inference.BeliefPropagation(gm, accumulator='integrator',
                                                   parameter=opengm.InfParam(steps=10,
                                                                             damping=0.5,
                                                                             convergenceBound=0.001))
# start inference (in this case unverbose infernce)

t0=time()
inf.infer(visitor)
t1=time()

# print t1-t0

begin
visit
energy  0.192
marginals [[ 0.3  0.7]]
visit
energy  0.192
marginals [[ 0.27334791  0.72665209]]
visit
energy  0.192
marginals [[ 0.23924715  0.76075285]]
visit
energy  0.192
marginals [[ 0.21209983  0.78790017]]
visit
energy  0.192
marginals [[ 0.19419384  0.80580616]]
visit
energy  0.192
marginals [[ 0.18336881  0.81663119]]
visit
energy  0.192
marginals [[ 0.1771794  0.8228206]]
visit
energy  0.192
marginals [[ 0.17383344  0.82616656]]
visit
energy  0.192
marginals [[ 0.17216053  0.82783947]]
visit
energy  0.192
marginals [[ 0.17143084  0.82856916]]
end


In [5]:
inf.marginals(0)

array([[ 0.17143084,  0.82856916]])

In [4]:
inf.marginals(1)

array([[ 0.91263834,  0.08736166]])

In [5]:
inf.marginals(2)

array([[ 0.80004287,  0.19995713]])

In [6]:
inf.factorMarginals(0)

array([[ 0.17634451,  0.82365549]])

In [7]:
inf.factorMarginals(1)

array([[[ 0.11768716,  0.05050971],
        [ 0.79523486,  0.03656827]]])

In [8]:
inf.factorMarginals(2)

array([[[ 0.15218053,  0.0270093 ],
        [ 0.64322628,  0.17758389]]])

In [9]:
inf.factorMarginals(3)

array([[[ 0.76985951,  0.14279581],
        [ 0.03372572,  0.05361896]]])